name = "SeparableFunctions"
authors = ["Rainer Heintzmann <heintzmann@gmail.com>"]
version = "0.1"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
SeparableFunctions = "c8c7ead4-852c-491e-a42d-3d43bc74259e"

[compat]
Documenter = "0.26"
